{
  "message": "TypeError: 'NoneType' object is not callable",
  "traceback": ["py_call_impl(callable, dots$args, dots$keywords)", "(structure(function (...) \n{\n    dots <- py_resolve_dots(list(...))\n    result <- py_call_impl(callable, dots$args, dots$keywords)\n    if (convert) \n        result <- py_to_r(result)\n    if (is.null(result)) \n        invisible(result)\n    else result\n}, class = c(\"python.builtin.method\", \"python.builtin.object\"\n), py_object = <environment>))(batch_size = 16L, epochs = 10L, \n    verbose = 1L, validation_split = 0, shuffle = TRUE, class_weight = NULL, \n    sample_weight = NULL, initial_epoch = 0L, x = <environment>, \n    callbacks = list(<environment>, <environment>))", "do.call(object$fit, args)", "fit.keras.engine.training.Model(., train_generator, train_generator$labels, \n    epochs = 10, batch_size = FLAGS$hl1)", "fit(., train_generator, train_generator$labels, epochs = 10, \n    batch_size = FLAGS$hl1)", "model %>% fit(train_generator, train_generator$labels, epochs = 10, \n    batch_size = FLAGS$hl1)", "eval(ei, envir)", "eval(ei, envir)", "training_run(\"cnn_assignment.R\", flags = c(hl1 = hl1))"]
}
